/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AMethodTextOutputOption extends POutputOption
{
    private TMethod _method_;
    private TEqual _equal_;
    private TTextFormat _textFormat_;

    public AMethodTextOutputOption()
    {
        // Constructor
    }

    public AMethodTextOutputOption(
        @SuppressWarnings("hiding") TMethod _method_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") TTextFormat _textFormat_)
    {
        // Constructor
        setMethod(_method_);

        setEqual(_equal_);

        setTextFormat(_textFormat_);

    }

    @Override
    public Object clone()
    {
        return new AMethodTextOutputOption(
            cloneNode(this._method_),
            cloneNode(this._equal_),
            cloneNode(this._textFormat_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodTextOutputOption(this);
    }

    public TMethod getMethod()
    {
        return this._method_;
    }

    public void setMethod(TMethod node)
    {
        if(this._method_ != null)
        {
            this._method_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._method_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public TTextFormat getTextFormat()
    {
        return this._textFormat_;
    }

    public void setTextFormat(TTextFormat node)
    {
        if(this._textFormat_ != null)
        {
            this._textFormat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textFormat_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._method_)
            + toString(this._equal_)
            + toString(this._textFormat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._method_ == child)
        {
            this._method_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._textFormat_ == child)
        {
            this._textFormat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._method_ == oldChild)
        {
            setMethod((TMethod) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._textFormat_ == oldChild)
        {
            setTextFormat((TTextFormat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
