/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleInnerElements extends PInnerElements
{
    private PInnerElements _innerElements_;
    private PInnerElement _innerElement_;

    public AMultipleInnerElements()
    {
        // Constructor
    }

    public AMultipleInnerElements(
        @SuppressWarnings("hiding") PInnerElements _innerElements_,
        @SuppressWarnings("hiding") PInnerElement _innerElement_)
    {
        // Constructor
        setInnerElements(_innerElements_);

        setInnerElement(_innerElement_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleInnerElements(
            cloneNode(this._innerElements_),
            cloneNode(this._innerElement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleInnerElements(this);
    }

    public PInnerElements getInnerElements()
    {
        return this._innerElements_;
    }

    public void setInnerElements(PInnerElements node)
    {
        if(this._innerElements_ != null)
        {
            this._innerElements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._innerElements_ = node;
    }

    public PInnerElement getInnerElement()
    {
        return this._innerElement_;
    }

    public void setInnerElement(PInnerElement node)
    {
        if(this._innerElement_ != null)
        {
            this._innerElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._innerElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._innerElements_)
            + toString(this._innerElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._innerElements_ == child)
        {
            this._innerElements_ = null;
            return;
        }

        if(this._innerElement_ == child)
        {
            this._innerElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._innerElements_ == oldChild)
        {
            setInnerElements((PInnerElements) newChild);
            return;
        }

        if(this._innerElement_ == oldChild)
        {
            setInnerElement((PInnerElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
