/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class ASingleOutputOptions extends POutputOptions
{
    private POutputOption _outputOption_;

    public ASingleOutputOptions()
    {
        // Constructor
    }

    public ASingleOutputOptions(
        @SuppressWarnings("hiding") POutputOption _outputOption_)
    {
        // Constructor
        setOutputOption(_outputOption_);

    }

    @Override
    public Object clone()
    {
        return new ASingleOutputOptions(
            cloneNode(this._outputOption_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleOutputOptions(this);
    }

    public POutputOption getOutputOption()
    {
        return this._outputOption_;
    }

    public void setOutputOption(POutputOption node)
    {
        if(this._outputOption_ != null)
        {
            this._outputOption_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outputOption_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._outputOption_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._outputOption_ == child)
        {
            this._outputOption_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._outputOption_ == oldChild)
        {
            setOutputOption((POutputOption) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
