/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class ASortingApplyTemplatesParameters extends PApplyTemplatesParameters
{
    private PSorting _sorting_;

    public ASortingApplyTemplatesParameters()
    {
        // Constructor
    }

    public ASortingApplyTemplatesParameters(
        @SuppressWarnings("hiding") PSorting _sorting_)
    {
        // Constructor
        setSorting(_sorting_);

    }

    @Override
    public Object clone()
    {
        return new ASortingApplyTemplatesParameters(
            cloneNode(this._sorting_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASortingApplyTemplatesParameters(this);
    }

    public PSorting getSorting()
    {
        return this._sorting_;
    }

    public void setSorting(PSorting node)
    {
        if(this._sorting_ != null)
        {
            this._sorting_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sorting_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sorting_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sorting_ == child)
        {
            this._sorting_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sorting_ == oldChild)
        {
            setSorting((PSorting) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
