/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import java.util.*;
import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AForEachTemplateContent extends PTemplateContent
{
    private TXsltTag _xsltTag_;
    private TForEach _open_;
    private TSelect _select_;
    private TEqual _equal_;
    private PText _text_;
    private TCloseTag _closeForEach_;
    private PSorting _sorting_;
    private final LinkedList<PTemplateContent> _templateContent_ = new LinkedList<PTemplateContent>();
    private TCloseXsltTag _closeXsltTag_;
    private TForEach _close_;
    private TCloseTag _closeXslt_;

    public AForEachTemplateContent()
    {
        // Constructor
    }

    public AForEachTemplateContent(
        @SuppressWarnings("hiding") TXsltTag _xsltTag_,
        @SuppressWarnings("hiding") TForEach _open_,
        @SuppressWarnings("hiding") TSelect _select_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") PText _text_,
        @SuppressWarnings("hiding") TCloseTag _closeForEach_,
        @SuppressWarnings("hiding") PSorting _sorting_,
        @SuppressWarnings("hiding") List<PTemplateContent> _templateContent_,
        @SuppressWarnings("hiding") TCloseXsltTag _closeXsltTag_,
        @SuppressWarnings("hiding") TForEach _close_,
        @SuppressWarnings("hiding") TCloseTag _closeXslt_)
    {
        // Constructor
        setXsltTag(_xsltTag_);

        setOpen(_open_);

        setSelect(_select_);

        setEqual(_equal_);

        setText(_text_);

        setCloseForEach(_closeForEach_);

        setSorting(_sorting_);

        setTemplateContent(_templateContent_);

        setCloseXsltTag(_closeXsltTag_);

        setClose(_close_);

        setCloseXslt(_closeXslt_);

    }

    @Override
    public Object clone()
    {
        return new AForEachTemplateContent(
            cloneNode(this._xsltTag_),
            cloneNode(this._open_),
            cloneNode(this._select_),
            cloneNode(this._equal_),
            cloneNode(this._text_),
            cloneNode(this._closeForEach_),
            cloneNode(this._sorting_),
            cloneList(this._templateContent_),
            cloneNode(this._closeXsltTag_),
            cloneNode(this._close_),
            cloneNode(this._closeXslt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForEachTemplateContent(this);
    }

    public TXsltTag getXsltTag()
    {
        return this._xsltTag_;
    }

    public void setXsltTag(TXsltTag node)
    {
        if(this._xsltTag_ != null)
        {
            this._xsltTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xsltTag_ = node;
    }

    public TForEach getOpen()
    {
        return this._open_;
    }

    public void setOpen(TForEach node)
    {
        if(this._open_ != null)
        {
            this._open_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._open_ = node;
    }

    public TSelect getSelect()
    {
        return this._select_;
    }

    public void setSelect(TSelect node)
    {
        if(this._select_ != null)
        {
            this._select_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._select_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public PText getText()
    {
        return this._text_;
    }

    public void setText(PText node)
    {
        if(this._text_ != null)
        {
            this._text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._text_ = node;
    }

    public TCloseTag getCloseForEach()
    {
        return this._closeForEach_;
    }

    public void setCloseForEach(TCloseTag node)
    {
        if(this._closeForEach_ != null)
        {
            this._closeForEach_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeForEach_ = node;
    }

    public PSorting getSorting()
    {
        return this._sorting_;
    }

    public void setSorting(PSorting node)
    {
        if(this._sorting_ != null)
        {
            this._sorting_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sorting_ = node;
    }

    public LinkedList<PTemplateContent> getTemplateContent()
    {
        return this._templateContent_;
    }

    public void setTemplateContent(List<PTemplateContent> list)
    {
        this._templateContent_.clear();
        this._templateContent_.addAll(list);
        for(PTemplateContent e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TCloseXsltTag getCloseXsltTag()
    {
        return this._closeXsltTag_;
    }

    public void setCloseXsltTag(TCloseXsltTag node)
    {
        if(this._closeXsltTag_ != null)
        {
            this._closeXsltTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeXsltTag_ = node;
    }

    public TForEach getClose()
    {
        return this._close_;
    }

    public void setClose(TForEach node)
    {
        if(this._close_ != null)
        {
            this._close_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._close_ = node;
    }

    public TCloseTag getCloseXslt()
    {
        return this._closeXslt_;
    }

    public void setCloseXslt(TCloseTag node)
    {
        if(this._closeXslt_ != null)
        {
            this._closeXslt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeXslt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._xsltTag_)
            + toString(this._open_)
            + toString(this._select_)
            + toString(this._equal_)
            + toString(this._text_)
            + toString(this._closeForEach_)
            + toString(this._sorting_)
            + toString(this._templateContent_)
            + toString(this._closeXsltTag_)
            + toString(this._close_)
            + toString(this._closeXslt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._xsltTag_ == child)
        {
            this._xsltTag_ = null;
            return;
        }

        if(this._open_ == child)
        {
            this._open_ = null;
            return;
        }

        if(this._select_ == child)
        {
            this._select_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._text_ == child)
        {
            this._text_ = null;
            return;
        }

        if(this._closeForEach_ == child)
        {
            this._closeForEach_ = null;
            return;
        }

        if(this._sorting_ == child)
        {
            this._sorting_ = null;
            return;
        }

        if(this._templateContent_.remove(child))
        {
            return;
        }

        if(this._closeXsltTag_ == child)
        {
            this._closeXsltTag_ = null;
            return;
        }

        if(this._close_ == child)
        {
            this._close_ = null;
            return;
        }

        if(this._closeXslt_ == child)
        {
            this._closeXslt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._xsltTag_ == oldChild)
        {
            setXsltTag((TXsltTag) newChild);
            return;
        }

        if(this._open_ == oldChild)
        {
            setOpen((TForEach) newChild);
            return;
        }

        if(this._select_ == oldChild)
        {
            setSelect((TSelect) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._text_ == oldChild)
        {
            setText((PText) newChild);
            return;
        }

        if(this._closeForEach_ == oldChild)
        {
            setCloseForEach((TCloseTag) newChild);
            return;
        }

        if(this._sorting_ == oldChild)
        {
            setSorting((PSorting) newChild);
            return;
        }

        for(ListIterator<PTemplateContent> i = this._templateContent_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTemplateContent) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._closeXsltTag_ == oldChild)
        {
            setCloseXsltTag((TCloseXsltTag) newChild);
            return;
        }

        if(this._close_ == oldChild)
        {
            setClose((TForEach) newChild);
            return;
        }

        if(this._closeXslt_ == oldChild)
        {
            setCloseXslt((TCloseTag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
