/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AIndentYesOutputOption extends POutputOption
{
    private TIndent _indent_;
    private TEqual _equal_;
    private TYes _yes_;

    public AIndentYesOutputOption()
    {
        // Constructor
    }

    public AIndentYesOutputOption(
        @SuppressWarnings("hiding") TIndent _indent_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") TYes _yes_)
    {
        // Constructor
        setIndent(_indent_);

        setEqual(_equal_);

        setYes(_yes_);

    }

    @Override
    public Object clone()
    {
        return new AIndentYesOutputOption(
            cloneNode(this._indent_),
            cloneNode(this._equal_),
            cloneNode(this._yes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIndentYesOutputOption(this);
    }

    public TIndent getIndent()
    {
        return this._indent_;
    }

    public void setIndent(TIndent node)
    {
        if(this._indent_ != null)
        {
            this._indent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._indent_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public TYes getYes()
    {
        return this._yes_;
    }

    public void setYes(TYes node)
    {
        if(this._yes_ != null)
        {
            this._yes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._yes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._indent_)
            + toString(this._equal_)
            + toString(this._yes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._indent_ == child)
        {
            this._indent_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._yes_ == child)
        {
            this._yes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._indent_ == oldChild)
        {
            setIndent((TIndent) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._yes_ == oldChild)
        {
            setYes((TYes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
