/*
 * NewJFrame.java
 *
 * Created on 4 czerwiec 2008, 18:32
 */

package project;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PushbackReader;
import javax.swing.JFileChooser;

import java.awt.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.event.*;

import xslt.lexer.Lexer;
import xslt.node.Start;
import xslt.parser.Parser;

/**
 *
 * @author  Administrator
 */
public class Main extends javax.swing.JFrame {
    String contentXslt,contentXML,name;
    private Translation translation;
    //FileInputStream file;
    BufferedReader buffer;
    Lexer lexer;
    final JFileChooser fc;
    /** Creates new form NewJFrame */
    public Main() {

     fc= new JFileChooser();

        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneXSLPreview = new javax.swing.JScrollPane();
        jTextAreaXSLPreview = new javax.swing.JTextArea();
        jScrollPaneHTMLCodePreview = new javax.swing.JScrollPane();
        jTextAreaHTMLCodePreview = new javax.swing.JTextArea();
        jTextFieldXSLfileName = new javax.swing.JTextField();
        jButtonChooseXSLFile = new javax.swing.JButton();
        jButtonGenerateHTML = new javax.swing.JButton();
        jLabelErrorReport = new javax.swing.JLabel();
        jScrollPaneHTMLPreview = new javax.swing.JScrollPane();
        jEditorPaneHTMLPreview = new javax.swing.JEditorPane();
        jLabelInfoHtmlPreview = new javax.swing.JLabel();
        jLabelInfoHTMLCodePreview = new javax.swing.JLabel();
        jLabelInfoErrorReport = new javax.swing.JLabel();
        jTextFieldXMLFileName = new javax.swing.JTextField();
        jButtonChooseXMLFile = new javax.swing.JButton();
        jScrollPaneXMLPreview = new javax.swing.JScrollPane();
        jEditorPaneXMLPreview = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Procesor XSLT");

        jTextAreaXSLPreview.setColumns(20);
        jTextAreaXSLPreview.setRows(5);
        jTextAreaXSLPreview.setEnabled(false);
        jScrollPaneXSLPreview.setViewportView(jTextAreaXSLPreview);

        jTextAreaHTMLCodePreview.setColumns(20);
        jTextAreaHTMLCodePreview.setRows(5);
        jScrollPaneHTMLCodePreview.setViewportView(jTextAreaHTMLCodePreview);

        jTextFieldXSLfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXSLfileNameActionPerformed(evt);
            }
        });

        jButtonChooseXSLFile.setText("Wybierz plik XSL");
        jButtonChooseXSLFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChooseXSLFileMouseClicked(evt);
            }
        });
        jButtonChooseXSLFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseXSLFileActionPerformed(evt);
            }
        });

        jButtonGenerateHTML.setText("Generuj plik html");
        jButtonGenerateHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateHTMLActionPerformed(evt);
            }
        });

        jEditorPaneHTMLPreview.setContentType("text/html");
        jScrollPaneHTMLPreview.setViewportView(jEditorPaneHTMLPreview);

        jLabelInfoHtmlPreview.setText("Podgląd HTML");

        jLabelInfoHTMLCodePreview.setText("Podgląd kodu html");

        jLabelInfoErrorReport.setText("Informacje o błędach:");

        jButtonChooseXMLFile.setText("Wybierz plik XML z danymi");
        jButtonChooseXMLFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseXMLFileActionPerformed(evt);
            }
        });

        jScrollPaneXMLPreview.setViewportView(jEditorPaneXMLPreview);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfoErrorReport)
                    .addComponent(jLabelErrorReport, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jScrollPaneXSLPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldXMLFileName)
                            .addComponent(jTextFieldXSLfileName, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonChooseXMLFile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonChooseXSLFile, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGenerateHTML)
                    .addComponent(jScrollPaneXMLPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInfoHTMLCodePreview)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPaneHTMLPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPaneHTMLCodePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jLabelInfoHtmlPreview)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonGenerateHTML)
                        .addComponent(jTextFieldXSLfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonChooseXSLFile))
                    .addComponent(jLabelInfoHTMLCodePreview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPaneHTMLCodePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInfoHtmlPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneHTMLPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneXMLPreview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonChooseXMLFile)
                                    .addComponent(jTextFieldXMLFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneXSLPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInfoErrorReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelErrorReport, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldXSLfileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXSLfileNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldXSLfileNameActionPerformed

    private void jButtonChooseXSLFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseXSLFileActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonChooseXSLFileActionPerformed

    private void jButtonChooseXSLFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChooseXSLFileMouseClicked
        // TODO add your handling code here:
        int returnVal = fc.showOpenDialog(jLabelErrorReport);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            name=file.getAbsolutePath();
            jTextFieldXSLfileName.setText(name);
            String linia = "";
            int line=1;
            contentXslt="";
            try{
            FileReader file2 = new FileReader(file);
            BufferedReader bfr = new BufferedReader(file2);
            while((linia = bfr.readLine()) != null){
                contentXslt+=line+":    "+linia+'\n';
                line++;
            }
        } catch( IOException ex ){
            System.out.println("Błąd przy operacji na pliku: "+ex);
        }
         System.out.println(contentXslt);
        jTextAreaXSLPreview.setText(contentXslt);
        }
}//GEN-LAST:event_jButtonChooseXSLFileMouseClicked

    private void jButtonGenerateHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateHTMLActionPerformed
       try {
// Create a Parser instance.
           
           lexer=new Lexer(new PushbackReader(new InputStreamReader(new FileInputStream (name)), 1024));
                
           Parser p =new Parser(lexer);
       
// Parse the input. 
		Start tree = p.parse();
		translation=new Translation();
		tree.apply(translation);
		jTextAreaHTMLCodePreview.setText(translation.getOutput());
                jLabelErrorReport.setText(translation.getErrors());
		//System.out.println(tree.toString());
                File html=new File(name+".html");
                FileWriter result=new FileWriter(html);
                jLabelErrorReport.setText(translation.getErrors());
                if(jLabelErrorReport.getText().contentEquals(translation.getErrors())){
                    result.write(jTextAreaHTMLCodePreview.getText());
                    jEditorPaneHTMLPreview.setText(jTextAreaHTMLCodePreview.getText());
                }
                result.close();
                
		}
// Apply the translation. 
		 catch(Exception e) { jLabelErrorReport.setText(e.getMessage());
                 }
}//GEN-LAST:event_jButtonGenerateHTMLActionPerformed

    private void jButtonChooseXMLFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseXMLFileActionPerformed
        // TODO add your handling code here:
        int returnVal = fc.showOpenDialog(jLabelErrorReport);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            name=file.getAbsolutePath();
            jTextFieldXMLFileName.setText(name);
            String linia = "";
            int line=1;
            contentXML="";
            try{
            FileReader file2 = new FileReader(file);
            BufferedReader bfr = new BufferedReader(file2);
            while((linia = bfr.readLine()) != null){
                contentXML+=line+":    "+linia+'\n';
                line++;
            }
        } catch( IOException ex ){
            System.out.println("Błąd przy operacji na pliku: "+ex);
        }
         System.out.println(contentXML);
        jEditorPaneXMLPreview.setText(contentXML);
        }
    }//GEN-LAST:event_jButtonChooseXMLFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChooseXMLFile;
    private javax.swing.JButton jButtonChooseXSLFile;
    private javax.swing.JButton jButtonGenerateHTML;
    private javax.swing.JEditorPane jEditorPaneHTMLPreview;
    private javax.swing.JEditorPane jEditorPaneXMLPreview;
    private javax.swing.JLabel jLabelErrorReport;
    private javax.swing.JLabel jLabelInfoErrorReport;
    private javax.swing.JLabel jLabelInfoHTMLCodePreview;
    private javax.swing.JLabel jLabelInfoHtmlPreview;
    private javax.swing.JScrollPane jScrollPaneHTMLCodePreview;
    private javax.swing.JScrollPane jScrollPaneHTMLPreview;
    private javax.swing.JScrollPane jScrollPaneXMLPreview;
    private javax.swing.JScrollPane jScrollPaneXSLPreview;
    private javax.swing.JTextArea jTextAreaHTMLCodePreview;
    private javax.swing.JTextArea jTextAreaXSLPreview;
    private javax.swing.JTextField jTextFieldXMLFileName;
    private javax.swing.JTextField jTextFieldXSLfileName;
    // End of variables declaration//GEN-END:variables
    
}
