/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class ATemplateInnerElement extends PInnerElement
{
    private PTemplateElement _templateElement_;

    public ATemplateInnerElement()
    {
        // Constructor
    }

    public ATemplateInnerElement(
        @SuppressWarnings("hiding") PTemplateElement _templateElement_)
    {
        // Constructor
        setTemplateElement(_templateElement_);

    }

    @Override
    public Object clone()
    {
        return new ATemplateInnerElement(
            cloneNode(this._templateElement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATemplateInnerElement(this);
    }

    public PTemplateElement getTemplateElement()
    {
        return this._templateElement_;
    }

    public void setTemplateElement(PTemplateElement node)
    {
        if(this._templateElement_ != null)
        {
            this._templateElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._templateElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._templateElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._templateElement_ == child)
        {
            this._templateElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._templateElement_ == oldChild)
        {
            setTemplateElement((PTemplateElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
