/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleOutputOptions extends POutputOptions
{
    private POutputOptions _outputOptions_;
    private POutputOption _outputOption_;

    public AMultipleOutputOptions()
    {
        // Constructor
    }

    public AMultipleOutputOptions(
        @SuppressWarnings("hiding") POutputOptions _outputOptions_,
        @SuppressWarnings("hiding") POutputOption _outputOption_)
    {
        // Constructor
        setOutputOptions(_outputOptions_);

        setOutputOption(_outputOption_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleOutputOptions(
            cloneNode(this._outputOptions_),
            cloneNode(this._outputOption_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleOutputOptions(this);
    }

    public POutputOptions getOutputOptions()
    {
        return this._outputOptions_;
    }

    public void setOutputOptions(POutputOptions node)
    {
        if(this._outputOptions_ != null)
        {
            this._outputOptions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outputOptions_ = node;
    }

    public POutputOption getOutputOption()
    {
        return this._outputOption_;
    }

    public void setOutputOption(POutputOption node)
    {
        if(this._outputOption_ != null)
        {
            this._outputOption_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outputOption_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._outputOptions_)
            + toString(this._outputOption_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._outputOptions_ == child)
        {
            this._outputOptions_ = null;
            return;
        }

        if(this._outputOption_ == child)
        {
            this._outputOption_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._outputOptions_ == oldChild)
        {
            setOutputOptions((POutputOptions) newChild);
            return;
        }

        if(this._outputOption_ == oldChild)
        {
            setOutputOption((POutputOption) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
