/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AText extends PText
{
    private TWords _words_;

    public AText()
    {
        // Constructor
    }

    public AText(
        @SuppressWarnings("hiding") TWords _words_)
    {
        // Constructor
        setWords(_words_);

    }

    @Override
    public Object clone()
    {
        return new AText(
            cloneNode(this._words_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAText(this);
    }

    public TWords getWords()
    {
        return this._words_;
    }

    public void setWords(TWords node)
    {
        if(this._words_ != null)
        {
            this._words_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._words_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._words_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._words_ == child)
        {
            this._words_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._words_ == oldChild)
        {
            setWords((TWords) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
