/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AApplyTemplates2TemplateContent extends PTemplateContent
{
    private TXsltTag _xsltTag_;
    private TApplyTemplates _applyTemplates_;
    private PApplyTemplatesOptions _applyTemplatesOptions_;
    private TCloseTagRange _closeTagRange_;

    public AApplyTemplates2TemplateContent()
    {
        // Constructor
    }

    public AApplyTemplates2TemplateContent(
        @SuppressWarnings("hiding") TXsltTag _xsltTag_,
        @SuppressWarnings("hiding") TApplyTemplates _applyTemplates_,
        @SuppressWarnings("hiding") PApplyTemplatesOptions _applyTemplatesOptions_,
        @SuppressWarnings("hiding") TCloseTagRange _closeTagRange_)
    {
        // Constructor
        setXsltTag(_xsltTag_);

        setApplyTemplates(_applyTemplates_);

        setApplyTemplatesOptions(_applyTemplatesOptions_);

        setCloseTagRange(_closeTagRange_);

    }

    @Override
    public Object clone()
    {
        return new AApplyTemplates2TemplateContent(
            cloneNode(this._xsltTag_),
            cloneNode(this._applyTemplates_),
            cloneNode(this._applyTemplatesOptions_),
            cloneNode(this._closeTagRange_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAApplyTemplates2TemplateContent(this);
    }

    public TXsltTag getXsltTag()
    {
        return this._xsltTag_;
    }

    public void setXsltTag(TXsltTag node)
    {
        if(this._xsltTag_ != null)
        {
            this._xsltTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xsltTag_ = node;
    }

    public TApplyTemplates getApplyTemplates()
    {
        return this._applyTemplates_;
    }

    public void setApplyTemplates(TApplyTemplates node)
    {
        if(this._applyTemplates_ != null)
        {
            this._applyTemplates_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._applyTemplates_ = node;
    }

    public PApplyTemplatesOptions getApplyTemplatesOptions()
    {
        return this._applyTemplatesOptions_;
    }

    public void setApplyTemplatesOptions(PApplyTemplatesOptions node)
    {
        if(this._applyTemplatesOptions_ != null)
        {
            this._applyTemplatesOptions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._applyTemplatesOptions_ = node;
    }

    public TCloseTagRange getCloseTagRange()
    {
        return this._closeTagRange_;
    }

    public void setCloseTagRange(TCloseTagRange node)
    {
        if(this._closeTagRange_ != null)
        {
            this._closeTagRange_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeTagRange_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._xsltTag_)
            + toString(this._applyTemplates_)
            + toString(this._applyTemplatesOptions_)
            + toString(this._closeTagRange_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._xsltTag_ == child)
        {
            this._xsltTag_ = null;
            return;
        }

        if(this._applyTemplates_ == child)
        {
            this._applyTemplates_ = null;
            return;
        }

        if(this._applyTemplatesOptions_ == child)
        {
            this._applyTemplatesOptions_ = null;
            return;
        }

        if(this._closeTagRange_ == child)
        {
            this._closeTagRange_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._xsltTag_ == oldChild)
        {
            setXsltTag((TXsltTag) newChild);
            return;
        }

        if(this._applyTemplates_ == oldChild)
        {
            setApplyTemplates((TApplyTemplates) newChild);
            return;
        }

        if(this._applyTemplatesOptions_ == oldChild)
        {
            setApplyTemplatesOptions((PApplyTemplatesOptions) newChild);
            return;
        }

        if(this._closeTagRange_ == oldChild)
        {
            setCloseTagRange((TCloseTagRange) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
