/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AStandaloneYesOutputOption extends POutputOption
{
    private TStandalone _standalone_;
    private TEqual _equal_;
    private TYes _yes_;

    public AStandaloneYesOutputOption()
    {
        // Constructor
    }

    public AStandaloneYesOutputOption(
        @SuppressWarnings("hiding") TStandalone _standalone_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") TYes _yes_)
    {
        // Constructor
        setStandalone(_standalone_);

        setEqual(_equal_);

        setYes(_yes_);

    }

    @Override
    public Object clone()
    {
        return new AStandaloneYesOutputOption(
            cloneNode(this._standalone_),
            cloneNode(this._equal_),
            cloneNode(this._yes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStandaloneYesOutputOption(this);
    }

    public TStandalone getStandalone()
    {
        return this._standalone_;
    }

    public void setStandalone(TStandalone node)
    {
        if(this._standalone_ != null)
        {
            this._standalone_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._standalone_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public TYes getYes()
    {
        return this._yes_;
    }

    public void setYes(TYes node)
    {
        if(this._yes_ != null)
        {
            this._yes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._yes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._standalone_)
            + toString(this._equal_)
            + toString(this._yes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._standalone_ == child)
        {
            this._standalone_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._yes_ == child)
        {
            this._yes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._standalone_ == oldChild)
        {
            setStandalone((TStandalone) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._yes_ == oldChild)
        {
            setYes((TYes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
