/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AAttributeTemplateContent extends PTemplateContent
{
    private PAttributeElement _attributeElement_;

    public AAttributeTemplateContent()
    {
        // Constructor
    }

    public AAttributeTemplateContent(
        @SuppressWarnings("hiding") PAttributeElement _attributeElement_)
    {
        // Constructor
        setAttributeElement(_attributeElement_);

    }

    @Override
    public Object clone()
    {
        return new AAttributeTemplateContent(
            cloneNode(this._attributeElement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributeTemplateContent(this);
    }

    public PAttributeElement getAttributeElement()
    {
        return this._attributeElement_;
    }

    public void setAttributeElement(PAttributeElement node)
    {
        if(this._attributeElement_ != null)
        {
            this._attributeElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributeElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributeElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributeElement_ == child)
        {
            this._attributeElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributeElement_ == oldChild)
        {
            setAttributeElement((PAttributeElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
