/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class ACopyOfTemplateContent extends PTemplateContent
{
    private TXsltTag _xsltTag_;
    private TCopyOf _copyOf_;
    private TSelect _select_;
    private TEqual _equal_;
    private PText _text_;
    private TCloseTagRange _closeTagRange_;

    public ACopyOfTemplateContent()
    {
        // Constructor
    }

    public ACopyOfTemplateContent(
        @SuppressWarnings("hiding") TXsltTag _xsltTag_,
        @SuppressWarnings("hiding") TCopyOf _copyOf_,
        @SuppressWarnings("hiding") TSelect _select_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") PText _text_,
        @SuppressWarnings("hiding") TCloseTagRange _closeTagRange_)
    {
        // Constructor
        setXsltTag(_xsltTag_);

        setCopyOf(_copyOf_);

        setSelect(_select_);

        setEqual(_equal_);

        setText(_text_);

        setCloseTagRange(_closeTagRange_);

    }

    @Override
    public Object clone()
    {
        return new ACopyOfTemplateContent(
            cloneNode(this._xsltTag_),
            cloneNode(this._copyOf_),
            cloneNode(this._select_),
            cloneNode(this._equal_),
            cloneNode(this._text_),
            cloneNode(this._closeTagRange_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACopyOfTemplateContent(this);
    }

    public TXsltTag getXsltTag()
    {
        return this._xsltTag_;
    }

    public void setXsltTag(TXsltTag node)
    {
        if(this._xsltTag_ != null)
        {
            this._xsltTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xsltTag_ = node;
    }

    public TCopyOf getCopyOf()
    {
        return this._copyOf_;
    }

    public void setCopyOf(TCopyOf node)
    {
        if(this._copyOf_ != null)
        {
            this._copyOf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._copyOf_ = node;
    }

    public TSelect getSelect()
    {
        return this._select_;
    }

    public void setSelect(TSelect node)
    {
        if(this._select_ != null)
        {
            this._select_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._select_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public PText getText()
    {
        return this._text_;
    }

    public void setText(PText node)
    {
        if(this._text_ != null)
        {
            this._text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._text_ = node;
    }

    public TCloseTagRange getCloseTagRange()
    {
        return this._closeTagRange_;
    }

    public void setCloseTagRange(TCloseTagRange node)
    {
        if(this._closeTagRange_ != null)
        {
            this._closeTagRange_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeTagRange_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._xsltTag_)
            + toString(this._copyOf_)
            + toString(this._select_)
            + toString(this._equal_)
            + toString(this._text_)
            + toString(this._closeTagRange_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._xsltTag_ == child)
        {
            this._xsltTag_ = null;
            return;
        }

        if(this._copyOf_ == child)
        {
            this._copyOf_ = null;
            return;
        }

        if(this._select_ == child)
        {
            this._select_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._text_ == child)
        {
            this._text_ = null;
            return;
        }

        if(this._closeTagRange_ == child)
        {
            this._closeTagRange_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._xsltTag_ == oldChild)
        {
            setXsltTag((TXsltTag) newChild);
            return;
        }

        if(this._copyOf_ == oldChild)
        {
            setCopyOf((TCopyOf) newChild);
            return;
        }

        if(this._select_ == oldChild)
        {
            setSelect((TSelect) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._text_ == oldChild)
        {
            setText((PText) newChild);
            return;
        }

        if(this._closeTagRange_ == oldChild)
        {
            setCloseTagRange((TCloseTagRange) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
