/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AMethodHtmlOutputOption extends POutputOption
{
    private TMethod _method_;
    private TEqual _equal_;
    private THtml _html_;

    public AMethodHtmlOutputOption()
    {
        // Constructor
    }

    public AMethodHtmlOutputOption(
        @SuppressWarnings("hiding") TMethod _method_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") THtml _html_)
    {
        // Constructor
        setMethod(_method_);

        setEqual(_equal_);

        setHtml(_html_);

    }

    @Override
    public Object clone()
    {
        return new AMethodHtmlOutputOption(
            cloneNode(this._method_),
            cloneNode(this._equal_),
            cloneNode(this._html_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodHtmlOutputOption(this);
    }

    public TMethod getMethod()
    {
        return this._method_;
    }

    public void setMethod(TMethod node)
    {
        if(this._method_ != null)
        {
            this._method_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._method_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public THtml getHtml()
    {
        return this._html_;
    }

    public void setHtml(THtml node)
    {
        if(this._html_ != null)
        {
            this._html_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._html_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._method_)
            + toString(this._equal_)
            + toString(this._html_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._method_ == child)
        {
            this._method_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._html_ == child)
        {
            this._html_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._method_ == oldChild)
        {
            setMethod((TMethod) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._html_ == oldChild)
        {
            setHtml((THtml) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
