/* This file was generated by SableCC (http://www.sablecc.org/). */

package xslt.node;

import xslt.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleTests extends PTests
{
    private PTests _tests_;
    private PTestElement _testElement_;

    public AMultipleTests()
    {
        // Constructor
    }

    public AMultipleTests(
        @SuppressWarnings("hiding") PTests _tests_,
        @SuppressWarnings("hiding") PTestElement _testElement_)
    {
        // Constructor
        setTests(_tests_);

        setTestElement(_testElement_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleTests(
            cloneNode(this._tests_),
            cloneNode(this._testElement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleTests(this);
    }

    public PTests getTests()
    {
        return this._tests_;
    }

    public void setTests(PTests node)
    {
        if(this._tests_ != null)
        {
            this._tests_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tests_ = node;
    }

    public PTestElement getTestElement()
    {
        return this._testElement_;
    }

    public void setTestElement(PTestElement node)
    {
        if(this._testElement_ != null)
        {
            this._testElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._testElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tests_)
            + toString(this._testElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tests_ == child)
        {
            this._tests_ = null;
            return;
        }

        if(this._testElement_ == child)
        {
            this._testElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tests_ == oldChild)
        {
            setTests((PTests) newChild);
            return;
        }

        if(this._testElement_ == oldChild)
        {
            setTestElement((PTestElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
